# inventory_data.py
inventory = [
    {'name': 'Laptop', 'category': 'Electronics', 'price': 999.99, 'stock': 10, 'rating': 4.5},
    {'name': 'Smartphone', 'category': 'Electronics', 'price': 699.00, 'stock': 15, 'rating': 4.7},
    {'name': 'Desk Chair', 'category': 'Furniture', 'price': 150.00, 'stock': 5, 'rating': 4.2},
    {'name': 'Bookcase', 'category': 'Furniture', 'price': 120.00, 'stock': 3, 'rating': 4.0},
    {'name': 'Headphones', 'category': 'Electronics', 'price': 199.00, 'stock': 20, 'rating': 4.3},
    {'name': 'Coffee Table', 'category': 'Furniture', 'price': 250.00, 'stock': 4, 'rating': 4.1},
    {'name': 'Bluetooth Speaker', 'category': 'Electronics', 'price': 89.00, 'stock': 18, 'rating': 4.4},
    {'name': 'Gaming Mouse', 'category': 'Electronics', 'price': 59.00, 'stock': 25, 'rating': 4.6},
    {'name': 'Office Desk', 'category': 'Furniture', 'price': 300.00, 'stock': 6, 'rating': 4.3},
    {'name': 'LED Monitor', 'category': 'Electronics', 'price': 229.00, 'stock': 12, 'rating': 4.5},
    {'name': 'Microwave Oven', 'category': 'Appliances', 'price': 180.00, 'stock': 8, 'rating': 4.2},
    {'name': 'Blender', 'category': 'Appliances', 'price': 75.00, 'stock': 10, 'rating': 4.1},
    {'name': 'Air Conditioner', 'category': 'Appliances', 'price': 499.00, 'stock': 5, 'rating': 4.6},
    {'name': 'Dining Table', 'category': 'Furniture', 'price': 550.00, 'stock': 2, 'rating': 4.4},
    {'name': 'Sofa', 'category': 'Furniture', 'price': 850.00, 'stock': 3, 'rating': 4.5},
    {'name': 'Smartwatch', 'category': 'Electronics', 'price': 299.00, 'stock': 14, 'rating': 4.3},
    {'name': 'Electric Kettle', 'category': 'Appliances', 'price': 45.00, 'stock': 20, 'rating': 4.0},
    {'name': 'Bookshelf Speaker', 'category': 'Electronics', 'price': 320.00, 'stock': 7, 'rating': 4.6},
    {'name': 'Recliner', 'category': 'Furniture', 'price': 400.00, 'stock': 4, 'rating': 4.2},
    {'name': 'Tablet', 'category': 'Electronics', 'price': 349.00, 'stock': 9, 'rating': 4.4},
    {'name': 'Standing Lamp', 'category': 'Furniture', 'price': 90.00, 'stock': 11, 'rating': 4.1},
    {'name': 'Air Fryer', 'category': 'Appliances', 'price': 130.00, 'stock': 6, 'rating': 4.5},
    {'name': 'Wireless Keyboard', 'category': 'Electronics', 'price': 70.00, 'stock': 13, 'rating': 4.3},
    {'name': 'Bookshelf', 'category': 'Furniture', 'price': 160.00, 'stock': 5, 'rating': 4.2},
    {'name': 'Smart TV', 'category': 'Electronics', 'price': 799.00, 'stock': 8, 'rating': 4.6},
    {'name': 'Toaster', 'category': 'Appliances', 'price': 35.00, 'stock': 10, 'rating': 4.0},
    {'name': 'Gaming Chair', 'category': 'Furniture', 'price': 220.00, 'stock': 6, 'rating': 4.5},
    {'name': 'Noise Cancelling Earbuds', 'category': 'Electronics', 'price': 149.00, 'stock': 17, 'rating': 4.4},
    {'name': 'Mini Fridge', 'category': 'Appliances', 'price': 250.00, 'stock': 3, 'rating': 4.3},
    {'name': 'Wall Clock', 'category': 'Furniture', 'price': 40.00, 'stock': 9, 'rating': 4.1},
    {'name': 'Electric Fan', 'category': 'Appliances', 'price': 60.00, 'stock': 15, 'rating': 4.2},
    {'name': 'Router', 'category': 'Electronics', 'price': 120.00, 'stock': 10, 'rating': 4.3},
    {'name': 'Printer', 'category': 'Electronics', 'price': 180.00, 'stock': 7, 'rating': 4.2},
    {'name': 'TV Stand', 'category': 'Furniture', 'price': 200.00, 'stock': 4, 'rating': 4.0},
    {'name': 'Rice Cooker', 'category': 'Appliances', 'price': 85.00, 'stock': 12, 'rating': 4.4},
    {'name': 'Floor Mat', 'category': 'Furniture', 'price': 35.00, 'stock': 20, 'rating': 4.1},
    {'name': 'Webcam', 'category': 'Electronics', 'price': 95.00, 'stock': 8, 'rating': 4.3},
    {'name': 'Projector', 'category': 'Electronics', 'price': 450.00, 'stock': 3, 'rating': 4.5},
    {'name': 'Water Dispenser', 'category': 'Appliances', 'price': 210.00, 'stock': 5, 'rating': 4.2},
]